package com.code.main;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class TeufelsfruchtDatabse {

	ArrayList<Teufelsfrucht> teufelsfruechte = new ArrayList<Teufelsfrucht>(Arrays.asList(
			new Teufelsfrucht("Gum-Gum-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, seinen Körper gummiartig zu dehnen."),
			new Teufelsfrucht("Feuer-Frucht", "Logia",
					"Ermöglicht es dem Verzehrer, Feuerkräfte zu erlangen und Feuer zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Sand-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Sand zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Blumen-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, beliebig viele Hände auf Oberflächen erscheinen zu lassen."),
			new Teufelsfrucht("Eis-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Eis zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Finster-Frucht", "Logia",
					"Ermöglicht es dem Verzehrer, Dunkelheit zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Gera-Gera-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, alles in seinem Umfeld in Gelächter ausbrechen zu lassen."),
			new Teufelsfrucht("Goro-Goro-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Elektrizität zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Schnee-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Schnee und Eis zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Blitz-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Licht zu erzeugen und sich mit Lichtgeschwindigkeit zu bewegen."),
			new Teufelsfrucht("Gas-Gas-Frucht", "Logia",
					"Ermöglicht es dem Verzehrer, Gas zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Magma-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Magma zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Blatt-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Blätter wachsen zu lassen und zu kontrollieren."),
			new Teufelsfrucht("Zucker-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, alles, was sie berührt, in Spielzeug zu verwandeln."),
			new Teufelsfrucht("Feuerwerk-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Feuerwerke aus den Händen zu schießen."),
			new Teufelsfrucht("Muster-Muster-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Muster auf Menschen oder Gegenstände zu projizieren."),
			new Teufelsfrucht("Diamant-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, sich in Diamant zu verwandeln und Diamanten zu erzeugen."),
			new Teufelsfrucht("Uhrwerk-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, seine Körperteile wie Uhrzeiger zu bewegen."),
			new Teufelsfrucht("Flammenkeks-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Flammenkeks-Körper und -Projektile zu erzeugen."),
			new Teufelsfrucht("Luft-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Luft zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Gravitation-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, die Gravitation zu kontrollieren."),
			new Teufelsfrucht("Tier-Tier-Frucht, Modell: Phönix", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in einen Phönix oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Raum-Frucht", "Logia",
					"Verleiht dem Verzehrer die Fähigkeit, Raum zu kontrollieren und Teleportation zu nutzen."),
			new Teufelsfrucht("Koch-Koch-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, köstliche Speisen zu erschaffen und zu manipulieren."),
			new Teufelsfrucht("Himmel-Himmel-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Flügel wachsen zu lassen und in die Lüfte aufzusteigen."),
			new Teufelsfrucht("Ton-Ton-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, sich in Ton zu verwandeln und diesen zu manipulieren."),
			new Teufelsfrucht("Illusions-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Illusionen zu erzeugen und andere zu täuschen."),
			new Teufelsfrucht("Schatten-Schatten-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Schatten zu manipulieren und Fähigkeiten von anderen zu stehlen."),
			new Teufelsfrucht("Drachen-Drachen-Frucht, Modell: T-Rex", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in einen T-Rex oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Schwert-Schwert-Frucht, Modell: Katana", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in ein lebendiges Katana oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Glas-Glas-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Glas zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Knochen-Knochen-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Knochen aus dem Körper zu manipulieren und als Waffen zu verwenden."),
			new Teufelsfrucht("Klang-Klang-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Klangwellen zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Kraft-Kraft-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, die körperliche Stärke von allem, was sie berühren, zu erhöhen."),
			new Teufelsfrucht("Licht-Licht-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Licht zu erzeugen und als Waffe einzusetzen."),
			new Teufelsfrucht("Stern-Stern-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Sterne zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Schnecke-Schnecke-Frucht", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in eine Riesenschnecke oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Zombie-Zombie-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Tote wiederzubeleben und als Zombies zu kontrollieren."),
			new Teufelsfrucht("Schlange-Schlange-Frucht", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in eine riesige Schlange oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Tanz-Tanz-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, mithilfe von Tanz verschiedenste Effekte zu erzeugen."),
			new Teufelsfrucht("Papier-Papier-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, sich in Papier zu verwandeln und Flugobjekte zu erschaffen."),
			new Teufelsfrucht("Puppe-Puppe-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Puppen zu erschaffen und diese zum Leben zu erwecken."),
			new Teufelsfrucht("Seelen-Seelen-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Seelen zu manipulieren und in Gegenstände oder Lebewesen zu übertragen."),
			new Teufelsfrucht("Feder-Feder-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Federn wachsen zu lassen und diese als Waffen einzusetzen."),
			new Teufelsfrucht("Nebel-Nebel-Frucht", "Logia",
					"Ermöglicht es dem Verzehrer, Nebel zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Tunnel-Tunnel-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Tunnel zu erschaffen und sich durch Oberflächen zu bewegen."),
			new Teufelsfrucht("Wachs-Wachs-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Wachs zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Gummiband-Gummiband-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, seinen Körper wie ein Gummiband zu dehnen und zu formen."),
			new Teufelsfrucht("Haut-Haut-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, seine Hauthärte und -beschaffenheit zu verändern."),
			new Teufelsfrucht("Fliege-Fliege-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, sich in eine Fliege oder eine Fliegen-Hybridform zu verwandeln."),
			new Teufelsfrucht("Kuss-Kuss-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Menschen oder Gegenstände zu küssen und ihre Fähigkeiten zu kopieren."),
			new Teufelsfrucht("Erde-Erde-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Erde zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Molch-Molch-Frucht", "Zoan",
					"Verleiht dem Verzehrer die Fähigkeit, sich in einen Molch oder eine Hybridform zu verwandeln."),
			new Teufelsfrucht("Panzer-Panzer-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, seinen Körper in einen unzerstörbaren Panzer zu verwandeln."),
			new Teufelsfrucht("Hologramm-Hologramm-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Hologramme zu erzeugen und damit zu täuschen."),
			new Teufelsfrucht("Stahl-Stahl-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Stahl zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Kamera-Kamera-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, alles, was sie fotografiert, zu verändern oder daraus Gegenstände zu erschaffen."),
			new Teufelsfrucht("Meteor-Meteor-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Meteore aus dem Himmel zu beschwören und zu kontrollieren."),
			new Teufelsfrucht("Kaktus-Kaktus-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, sich in einen Kaktus zu verwandeln und Dornen zu nutzen."),
			new Teufelsfrucht("Glasur-Glasur-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, alles, was sie berührt, mit einer harten Glasur zu überziehen."),
			new Teufelsfrucht("Klinge-Klinge-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, aus Körperteilen scharfe Klingen wachsen zu lassen."),
			new Teufelsfrucht("Tornado-Tornado-Frucht", "Logia",
					"Ermöglicht es dem Verzehrer, Tornados zu erzeugen und zu kontrollieren."),
			new Teufelsfrucht("Thermometer-Thermometer-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, die Temperatur von allem, was sie berühren, zu manipulieren."),
			new Teufelsfrucht("Maske-Maske-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Gesichtszüge zu verändern und sich in andere Personen zu verwandeln."),
			new Teufelsfrucht("Sandwich-Sandwich-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, beliebige Objekte zwischen flachen Schichten zu verbergen."),
			new Teufelsfrucht("Stempel-Stempel-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, Stempel aus der Handfläche zu erschaffen und damit alles zu markieren."),
			new Teufelsfrucht("Dünger-Dünger-Frucht", "Paramecia",
					"Ermöglicht es dem Verzehrer, Pflanzenwachstum zu beschleunigen und kontrollieren."),
			new Teufelsfrucht("Sprung-Sprung-Frucht", "Paramecia",
					"Verleiht dem Verzehrer die Fähigkeit, unglaublich hoch zu springen und schweben zu können.")));

	public Teufelsfrucht getTeufelsfruchtByName(String name) {

		for (Teufelsfrucht teufelsfrucht : teufelsfruechte) {
			if (name.equals(teufelsfrucht.getName())) {
				return teufelsfrucht;

			}

		}
		throw new IllegalArgumentException("Teufelsfrucht mit dem Namen \"" + name + "\" wurde nicht gefunden.");

	}

	public Teufelsfrucht getTeufelsfruchtRandom() {
		Random randomNumber = new Random();
		return teufelsfruechte.get(randomNumber.nextInt(teufelsfruechte.size()));

	}

}
